sudo: false
language: node_js
node_js:
  - 4
  - 6
matrix:
  fast_finish: true
env:
  global:
    - CXX=g++-4.8
  matrix:
    - TEST_SUITE=units
script: npm run $TEST_SUITE
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm prune
